version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
      POSTGRES_USER: ${POSTGRES_USER:-docker}
    ports:
      - '${DB_PORT:-5552}:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
volumes:
  db:

